CREATE DATABASE rsprojekat CHARACTER SET "utf8mb4";
USE rsprojekat;

CREATE TABLE mjesto (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    naziv VARCHAR(100) NOT NULL
);

CREATE TABLE lokacija (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    naziv VARCHAR(100) NOT NULL,
    id_mjesto INT NOT NULL,
    FOREIGN KEY (id_mjesto) REFERENCES mjesto(id)
);